# Default values
DOWNLOAD_URL=https://www.github.com/Avinashreddy231p/ProjectMusic/releases/latest
DONATION_LINK=https://ko-fi.com/christiaam
GITHUB_API_URL=https://api.github.com/
LYRICALLY_API_URL=https://lyrics.paxsenix.org/apple-music/lyrics
